# Usamos una versión ligera de Python
FROM python:3.11-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos de tu proyecto
COPY . .

# Instalamos Flask
RUN pip install flask

# Exponemos el puerto 5000
EXPOSE 5000

# Comando para arrancar la app
CMD ["python", "app.py"]